---
environments:
  dev:
    docker:
      APP: app
      VERSION: "0.1"
      registry: ecr
      url: .dkr.ecr.us-east-1.amazonaws.com/project
      platforms: linux/amd64,linux/arm64
      filename: Dockerfile
      filepath: .
      arguments:
        APP: "{{ APP }}"
        VERSION: "{{ VERSION }}"

    microservice:
      cluster: name
      cpu: 128
      memory: 64
      replicas: 1
      domain_name: fastapi.dev.x.com
      variables:
        DATABASE: louvre
        USERNAME: admin
      secrets:
        PASSWORD: arn:aws:secretsmanager:<region>:<account>:secret:dev/db/app/password-kg6Fjj
        ENDPOINT: arn:aws:secretsmanager:<region>:<account>:secret:dev/db/app/endpoint-d6lQNT
...
