---
environments:
  dev:
    docker:
      registry: ecr
      url: 199920436475.dkr.ecr.us-east-1.amazonaws.com
      filename: Dockerfile
      filepath: .
      arguments:
        APP: golang
        VERSION: "0.0"

    microservice:
      cluster: dev-ecs_cluster
      cpu:  128
      memory: 64
      replicas: 2
      domain_name: fastapi.dev.edeluquez.com
      variables:
        DATABASE: louvre2
        USERNAME: admin
      secrets:
        PASSWORD: dev/db/fastapi/password
        ENDPOINT: dev/db/fastapi/endpoint
...
