---
environments:
  dev:
    docker:
      APP: fastapi
      VERSION: "0.0"
      registry: ecr
      url: 199920436475.dkr.ecr.us-east-1.amazonaws.com
      platforms: linux/amd64,linux/arm64
      filename: Dockerfile
      filepath: .
      arguments:
        APP: {{ APP }}
        VERSION: {{ VERSION }}

    microservice:
      cluster: dev-ecs_cluster
      cpu: 128
      memory: 64
      replicas: 2
      domain_name: fastapi.dev.edeluquez.com
      variables:
        DATABASE: louvre19
        USERNAME: admin
      secrets:
        PASSWORD: dev/db/fastapi/password
        ENDPOINT: dev/db/fastapi/endpoint
...
